apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        
        - name: WORDPRESS_DB_USER
          value: "user"
        - name: WORDPRESS_DB_NAME
          value: "database"
        - name: WORDPRESS_DB_HOST
          value: "mysql-service.database.svc.cluster.local"
        
        
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        
        
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
